version: '3.7'
services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native interface for ClickHouse client
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_DB: default
    volumes:
    - clickhouse_data:/var/lib/clickhouse

volumes:
  clickhouse_data:
